In [127]:
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("GPU not detected")

PyTorch version: 2.11.0+cu130
CUDA available: True
GPU: Tesla T4
CUDA version: 13.0

In [128]:
import requests
import pandas as pd

url = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"

params = {
    "$limit": 100000,
    "$where": "created_date >= '2026-03-01T00:00:00'",
    "$order": "created_date ASC"
}

response = requests.get(url, params=params)
response.raise_for_status()

data = response.json()

df = pd.DataFrame(data)

print("Dataset shape:", df.shape)

print("\nDate range:")
print("Oldest :", df["created_date"].min())
print("Latest :", df["created_date"].max())

print("\nStatus distribution:")
print(df["status"].value_counts())

df.head()

Dataset shape: (100000, 44)

Date range:
Oldest : 2026-03-01T00:00:07.000
Latest : 2026-03-09T23:15:38.000

Status distribution:
status
Closed         96628
Open            1347
In Progress     1280
Pending          466
Assigned         211
Started           67
Unspecified        1
Name: count, dtype: int64

,unique_key,created_date,closed_date,agency,agency_name,complaint_type,descriptor,location_type,incident_zip,incident_address,...,descriptor_2,bridge_highway_name,bridge_highway_segment,vehicle_type,facility_type,bridge_highway_direction,road_ramp,taxi_pick_up_location,taxi_company_borough,due_date
0,68166342,2026-03-01T00:00:07.000,2026-03-01T02:49:39.000,NYPD,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,Street/Sidewalk,11230,855 EAST 19 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,68163601,2026-03-01T00:00:20.000,2026-03-01T00:35:08.000,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Talking,Street/Sidewalk,10468,36 EAST BEDFORD PARK BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,68163320,2026-03-01T00:00:36.000,2026-03-01T00:58:36.000,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10457,2161 CLINTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,68166371,2026-03-01T00:00:40.000,2026-03-01T02:43:43.000,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11216,1161 DEAN STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,68157778,2026-03-01T00:00:52.000,2026-03-01T00:56:08.000,NYPD,New York City Police Department,Noise - Residential,Loud Talking,Residential Building/House,10009,540 EAST 5 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
print("Shape:", df.shape)

print("\nColumn names and data types:")
print(df.dtypes.to_string())

Shape: (100000, 44)

Column names and data types:
unique_key                        object
created_date                      object
closed_date                       object
agency                            object
agency_name                       object
complaint_type                    object
descriptor                        object
location_type                     object
incident_zip                      object
incident_address                  object
street_name                       object
cross_street_1                    object
cross_street_2                    object
intersection_street_1             object
intersection_street_2             object
address_type                      object
city                              object
landmark                          object
status                            object
resolution_description            object
resolution_action_updated_date    object
community_board                   object
council_district                  object
police_precinct                   object
bbl                               object
borough                           object
x_coordinate_state_plane          object
y_coordinate_state_plane          object
open_data_channel_type            object
park_facility_name                object
park_borough                      object
latitude                          object
longitude                         object
location                          object
descriptor_2                      object
bridge_highway_name               object
bridge_highway_segment            object
vehicle_type                      object
facility_type                     object
bridge_highway_direction          object
road_ramp                         object
taxi_pick_up_location             object
taxi_company_borough              object
due_date                          object

In [88]:
missing_analysis = pd.DataFrame({
    'missing_count': df.isnull().sum(),
    'missing_percentage': (df.isnull().mean() * 100).round(2),
    'unique_values': df.nunique(dropna=True)
})

missing_analysis = missing_analysis.sort_values(
    'missing_percentage',
    ascending=False
)

missing_analysis

TypeError: unhashable type: 'dict'

In [89]:
for col in df.columns:
    dict_count = df[col].apply(lambda x: isinstance(x, dict)).sum()
    list_count = df[col].apply(lambda x: isinstance(x, list)).sum()

    if dict_count > 0 or list_count > 0:
        print(
            f"{col}: "
            f"{dict_count} dictionaries, "
            f"{list_count} lists"
        )

location: 95005 dictionaries, 0 lists

In [90]:
missing_analysis = pd.DataFrame({
    'missing_count': df.isnull().sum(),
    'missing_percentage': (df.isnull().mean() * 100).round(2),
})

# Calculate unique values safely
unique_values = {}

for col in df.columns:
    if col == 'location':
        # Location is a dictionary, so count unique representations
        unique_values[col] = df[col].dropna().apply(str).nunique()
    else:
        unique_values[col] = df[col].nunique(dropna=True)

missing_analysis['unique_values'] = pd.Series(unique_values)

missing_analysis = missing_analysis.sort_values(
    'missing_percentage',
    ascending=False
)

missing_analysis

,missing_count,missing_percentage,unique_values
taxi_company_borough,99905,99.90,5
due_date,99669,99.67,241
taxi_pick_up_location,99146,99.15,619
road_ramp,99055,99.06,31
bridge_highway_direction,99040,99.04,71
bridge_highway_name,98876,98.88,57
bridge_highway_segment,98875,98.88,367
vehicle_type,95210,95.21,8
facility_type,86847,86.85,2
descriptor_2,51907,51.91,542
landmark,46796,46.80,4239
intersection_street_1,35933,35.93,4874
intersection_street_2,35909,35.91,4991
cross_street_2,33932,33.93,6756
cross_street_1,33923,33.92,6773
location_type,17956,17.96,101
bbl,17358,17.36,37798
street_name,7669,7.67,5749
incident_address,7667,7.67,45470
city,5497,5.50,54
council_district,5415,5.42,51
longitude,4995,5.00,47828
location,4995,5.00,47828
latitude,4995,5.00,47828
x_coordinate_state_plane,4992,4.99,34859
y_coordinate_state_plane,4982,4.98,38494
closed_date,3169,3.17,68563
incident_zip,1708,1.71,221
address_type,1151,1.15,5
resolution_description,870,0.87,470
resolution_action_updated_date,638,0.64,61563
agency_name,0,0.00,16
created_date,0,0.00,81260
unique_key,0,0.00,100000
descriptor,0,0.00,677
agency,0,0.00,16
complaint_type,0,0.00,161
police_precinct,0,0.00,78
community_board,0,0.00,77
status,0,0.00,7
borough,0,0.00,6
park_facility_name,0,0.00,34
park_borough,0,0.00,6
open_data_channel_type,0,0.00,5

In [91]:
core_columns = [
    'unique_key',
    'created_date',
    'closed_date',
    'agency',
    'complaint_type',
    'descriptor',
    'borough',
    'status',
    'resolution_description'
]

df_core = df[core_columns].copy()

print("Core dataset shape:", df_core.shape)
df_core.head()

Core dataset shape: (100000, 9)

,unique_key,created_date,closed_date,agency,complaint_type,descriptor,borough,status,resolution_description
0,68166342,2026-03-01T00:00:07.000,2026-03-01T02:49:39.000,NYPD,Illegal Parking,Posted Parking Sign Violation,BROOKLYN,Closed,The New York City Police Department responded ...
1,68163601,2026-03-01T00:00:20.000,2026-03-01T00:35:08.000,NYPD,Noise - Street/Sidewalk,Loud Talking,BRONX,Closed,The New York City Police Department responded ...
2,68163320,2026-03-01T00:00:36.000,2026-03-01T00:58:36.000,NYPD,Blocked Driveway,No Access,BRONX,Closed,The New York City Police Department responded ...
3,68166371,2026-03-01T00:00:40.000,2026-03-01T02:43:43.000,NYPD,Noise - Residential,Loud Music/Party,BROOKLYN,Closed,The New York City Police Department responded ...
4,68157778,2026-03-01T00:00:52.000,2026-03-01T00:56:08.000,NYPD,Noise - Residential,Loud Talking,MANHATTAN,Closed,The New York City Police Department responded ...

In [92]:
print("Shape:", df_core.shape)

print("\nData types:")
print(df_core.dtypes)

print("\nMissing values:")
print(df_core.isnull().sum())

Shape: (100000, 9)

Data types:
unique_key                object
created_date              object
closed_date               object
agency                    object
complaint_type            object
descriptor                object
borough                   object
status                    object
resolution_description    object
dtype: object

Missing values:
unique_key                   0
created_date                 0
closed_date               3169
agency                       0
complaint_type               0
descriptor                   0
borough                      0
status                       0
resolution_description     870
dtype: int64

In [93]:
status_counts = df_core['status'].value_counts()

status_percentage = (
    df_core['status']
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

status_summary = pd.DataFrame({
    'count': status_counts,
    'percentage': status_percentage
})

status_summary

             count  percentage
status
Closed       96623       96.62
Open          1349        1.35
In Progress   1281        1.28
Pending        466        0.47
Assigned       212        0.21
Started         68        0.07
Unspecified      1        0.00

In [94]:
status_resolution_check = pd.crosstab(
    df_core['status'],
    df_core['resolution_description'].isna(),
    margins=True
)

status_resolution_check.columns = [
    'Resolution Available',
    'Resolution Missing',
    'Total'
]

status_resolution_check

             Resolution Available  Resolution Missing   Total
status
Assigned                      212                   0     212
Closed                      96440                 183   96623
In Progress                   616                 665    1281
Open                         1328                  21    1349
Pending                       466                   0     466
Started                        68                   0      68
Unspecified                     0                   1       1
All                         99130                 870  100000

In [95]:
complaint_counts = (
    df_core['complaint_type']
    .value_counts()
    .head(20)
)

complaint_counts

complaint_type
Illegal Parking             15332
Noise - Residential         10236
HEAT/HOT WATER               9794
Street Condition             7296
Blocked Driveway             4938
Traffic Signal Condition     3300
Noise - Street/Sidewalk      3211
UNSANITARY CONDITION         3004
Dirty Condition              2647
Abandoned Vehicle            2099
PLUMBING                     2039
PAINT/PLASTER                1743
Noise                        1582
Noise - Commercial           1482
WATER LEAK                   1337
Water System                 1335
DOOR/WINDOW                  1320
Noise - Vehicle              1308
Derelict Vehicles            1114
Street Light Condition       1022
Name: count, dtype: int64

In [96]:
print("Unique complaint types:", df_core['complaint_type'].nunique())
print("Unique descriptors:", df_core['descriptor'].nunique())

print("\nTop 30 descriptors:")
print(df_core['descriptor'].value_counts().head(30))

Unique complaint types: 161
Unique descriptors: 677

Top 30 descriptors:
descriptor
Loud Music/Party                  9134
ENTIRE BUILDING                   6457
Pothole                           5661
Blocked Hydrant                   4328
Banging/Pounding                  3922
Posted Parking Sign Violation     3918
No Access                         3754
APARTMENT ONLY                    3337
Trash                             2321
Controller                        2261
With License Plate                2099
Blocked Sidewalk                  1973
Loud Talking                      1756
PESTS                             1464
N/A                               1320
Partial Access                    1184
Derelict Vehicles                 1114
Blocked Crosswalk                 1030
Commercial Overnight Parking       942
MOLD                               941
Double Parked Blocking Traffic     924
CEILING                            845
Removal Request                    836
Cave-in                            800
Street Light Out                   800
WALL                               793
FLOOR                              790
DOOR                               723
Pothole - Highway                  685
Parking Permit Improper Use        644
Name: count, dtype: int64

In [97]:
for col in ['complaint_type', 'descriptor', 'borough', 'resolution_description']:
    print(f"\n--- {col} ---")
    print("Missing:", df_core[col].isna().sum())
    print("N/A:", (df_core[col].astype(str).str.strip().str.upper() == 'N/A').sum())
    print("Unique:", df_core[col].nunique())

--- complaint_type ---
Missing: 0
N/A: 0
Unique: 161

--- descriptor ---
Missing: 0
N/A: 1320
Unique: 677

--- borough ---
Missing: 0
N/A: 0
Unique: 6

--- resolution_description ---
Missing: 870
N/A: 453
Unique: 470

In [98]:
resolution_counts = (
    df_core['resolution_description']
    .dropna()
    .value_counts()
)

print("Unique non-null resolutions:", resolution_counts.shape[0])

print("\nTop 30 resolution descriptions:")
for i, (resolution, count) in enumerate(resolution_counts.head(30).items(), 1):
    print(f"{i:2}. [{count:5}] {resolution}")

Unique non-null resolutions: 470

Top 30 resolution descriptions:
 1. [10723] The New York City Police Department responded to the complaint and with the information available observed no evidence of a criminal violation at that time. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. If necessary, your complaint may be referred to your local precinct's special operations units (Quality of Life, etc.). We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
 2. [ 9040] The New York City Police Department responded to the complaint and their investigation determined that no criminal violation existed. The condition was corrected without the need to issue a summons or effect an arrest. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. If necessary, your complaint may be referred to your local precinct's special operations units (Quality of Life, etc.). Thank you for your attention to this matter. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
 3. [ 6347] The New York City Police Department responded to the complaint and their investigation determined that police action was not necessary. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
 4. [ 6071] The New York City Police Department responded to the complaint and observed no criminal violation upon their arrival. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
 5. [ 5878] The New York City Police Department responded to the complaint and their investigation determined that a violation of law occurred. Police issued a summons in response to the complaint. Thank you for attention to this matter. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
 6. [ 3904] HPD conducted an inspection of this complaint. The conditions observed by the inspector did not violate the housing laws enforced by HPD. The complaint has been closed.
 7. [ 3811] Service Request status for this request is available on the Department of Transportationâs website. Please click the âLearn Moreâ link below.
 8. [ 3096] This complaint is a duplicate of a building-wide condition already reported by another tenant.  The original complaint is still open, and HPD may only need to confirm that the condition exists by inspecting one apartment.  If we cannot contact the tenant from the original complaint or get access to that apartment, HPD may attempt to contact the person who filed this complaint to verify the correction of the condition or may conduct an inspection of your unit. You can check HPDONLINE to see if a
 9. [ 2864] HPD inspected this condition so the complaint has been closed. Violations were issued. The law provides the property owner time to correct the condition(s).  Violation descriptions and the dates for the property owner to correct any violations are available at HPDONLINE.  If the owner has not corrected the condition by the date provided, you may wish to bring a case in housing court seeking the correction of these conditions.To find out more about how to start a housing court case, visit HPD's w
10. [ 2781] The Department of Transportation inspected this complaint and repaired the problem.
11. [ 2745] HPD attempted to conduct an inspection in response to this complaint, but was unable to complete the inspection. Please submit a new service request with 311 if the condition still exists. For more information on the reason why HPD was unable to inspect, contact HPD at the Tenant Information Messaging Service at 212-863-4951.
12. [ 2066] An HPD Inspector was not able to gain access to inspect this complaint. The Inspector left a card at the time of the inspection and a letter was sent from HPD after the inspection attempt to encourage you to call to schedule an inspection. HPD did not receive a timely response from you and the complaint has been closed. Please submit a new service request with 311 if the condition still exists.
13. [ 1902] The Department of Transportation determined that this complaint is a duplicate of a previously filed complaint. The original complaint is being addressed.
14. [ 1547] HPD responded to a complaint of no heat or hot water in the building. An occupant of the building confirmed heat and hot water had been restored when the Inspector attempted to conduct the inspection or contacted you at the phone number associated with the complaint. The complaint has been closed. Please submit a new service request with 311 if the condition still exists.
15. [ 1489] The Department of Sanitation investigated this complaint and found no condition at the location.
16. [ 1356] The New York City Police Department responded to the complaint but officers were unable to gain entry into the premises. If the problem persists, please contact 311 to create another complaint and ensure that contact information (e.g., buzzer number, phone number, etc.) is available to assist the responding officers in gaining entry to properly investigate the complaint.  We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.
17. [ 1217] The following complaint conditions are still open. HPD has already attempted to notify the property owner that the condition exists; the tenant should provide access for the owner to make the repair.  HPD may attempt to contact the tenant by phone to verify the correction of the condition or an HPD Inspector may attempt to conduct an inspection.
18. [ 1128] The Department of Housing Preservation and Development was not able to gain access to your apartment or others in the building to inspect for a lack of heat or hot water. The complaint has been closed. If the condition still exists, please file a new complaint.
19. [ 1111] HPD called the telephone number on file for this complaint.  Someone at that number indicated that the condition was corrected. The complaint has been closed. Please submit a new service request with 311 if the condition still exists.
20. [ 1092] The Department of Transportation has completed the request or corrected the condition.
21. [ 1001] The Department of Housing Preservation and Development conducted or attempted to conduct an inspection.  More information about inspection results can be found through HPD's website at www.nyc.gov/hpd by using HPDONLINE (enter your address on the home page) and entering your SR number under the complaint status option.
22. [  967] The Department of Sanitation cleaned the location.
23. [  944] The Department of Sanitation investigated this complaint and found no violation at the location.
24. [  933] The Department of Buildings investigated this complaint and determined that no further action was necessary.
25. [  929] The Department of Environmental Protection (DEP) didn't observe a violation of the NYC Air or Noise Code at the time of inspection and couldn't issue a summons.  If the problem still exists, please go to nyc.gov/311 or call 311 to file a new Service Request. If you're outside of New York City, please call (212) NEW-YORK (212-639-9675).
26. [  834] The Department of Environmental Protection determined that this complaint is a duplicate of a previously filed complaint. The original complaint is being addressed.
27. [  801] The Department of Housing Preservation and Development inspected the following conditions. No violations were issued. The complaint has been closed.
28. [  799] The Department of Sanitation investigated this complaint and issued a Notice of Violation.
29. [  670] The Department of Housing Preservation and Development contacted a tenant in the building and verified that the following conditions were corrected. The complaint has been closed. If the condition still exists, please file a new complaint.
30. [  536] Your complaint has been received but does not fall under the jurisdiction of the New York City Police Department.  Please contact your local precinct for more information, including which City agency your request was referred to. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.

In [99]:
resolution_diversity = (
    df_core[df_core['resolution_description'].notna()]
    .groupby('complaint_type')['resolution_description']
    .nunique()
    .sort_values(ascending=False)
)

print("Complaint types with most distinct resolutions:")
print(resolution_diversity.head(50))

Complaint types with most distinct resolutions:
complaint_type
Street Condition                           41
Sidewalk Condition                         40
Sewer                                      31
Consumer Complaint                         29
General Construction/Plumbing              26
Curb Condition                             23
Building/Use                               22
Obstruction                                21
WATER LEAK                                 19
Water System                               17
PAINT/PLASTER                              17
UNSANITARY CONDITION                       17
Damaged Tree                               15
HEAT/HOT WATER                             15
Special Projects Inspection Team (SPIT)    15
Noise                                      15
Derelict Vehicles                          14
Maintenance or Facility                    14
Street Sign - Damaged                      14
Dirty Condition                            14
Indoor Air Quality                         14
Water Conservation                         14
Illegal Dumping                            13
Real Time Enforcement                      13
Plumbing                                   13
PLUMBING                                   13
Animal in a Park                           13
Highway Condition                          13
DOOR/WINDOW                                13
Illegal Parking                            13
ELECTRIC                                   12
Illegal Tree Damage                        12
Abandoned Vehicle                          12
Asbestos                                   12
Abandoned Bike                             11
Overgrown Tree/Branches                    11
Snow or Ice                                11
Panhandling                                11
GENERAL                                    11
Cannabis Retailer                          11
Litter Basket Request                      11
Graffiti                                   11
Emergency Response Team (ERT)              10
Violation of Park Rules                    10
Street Sweeping Complaint                  10
APPLIANCE                                  10
Blocked Driveway                           10
Sanitation Worker or Vehicle Complaint     10
SAFETY                                     10
Dead/Dying Tree                            10
Name: resolution_description, dtype: int64

In [100]:
# 1. Number of unique complaint types
num_complaint_types = df_core['complaint_type'].nunique()

# 2. Number of unique descriptors for each complaint type
descriptors_per_complaint = (
    df_core.groupby('complaint_type')['descriptor']
    .nunique()
    .sort_values(ascending=False)
)

# 3. Number of unique resolutions for each descriptor
resolutions_per_descriptor = (
    df_core[df_core['resolution_description'].notna()]
    .groupby('descriptor')['resolution_description']
    .nunique()
    .sort_values(ascending=False)
)

print("Number of unique complaint types:", num_complaint_types)

print("\nTop 30 complaint types by number of descriptors:")
print(descriptors_per_complaint.head(30))

print("\nTop 30 descriptors by number of distinct resolutions:")
print(resolutions_per_descriptor.head(30))

Number of unique complaint types: 161

Top 30 complaint types by number of descriptors:
complaint_type
Consumer Complaint                59
Traffic Signal Condition          41
General Construction/Plumbing     27
Street Light Condition            27
Food Establishment                25
Street Condition                  18
Sidewalk Condition                16
Sewer                             14
Illegal Parking                   14
Noise                             13
Street Sign - Damaged             13
Water System                      13
Street Sign - Dangling            13
Maintenance or Facility           11
Street Sign - Missing             11
Highway Condition                 11
Broken Parking Meter               9
Water Quality                      9
Air Quality                        9
Residential Disposal Complaint     9
PLUMBING                           8
Water Conservation                 8
Dead Animal                        8
Animal in a Park                   7
Obstruction                        7
GENERAL                            7
Overgrown Tree/Branches            7
Violation of Park Rules            7
Mobile Food Vendor                 7
Water Maintenance                  7
Name: descriptor, dtype: int64

Top 30 descriptors by number of distinct resolutions:
descriptor
Broken Sidewalk                                       26
Cave-in                                               24
N/A                                                   20
Illegal Conversion Of Residential Building/Space      18
Rough, Pitted or Cracked Roads                        18
Trash                                                 17
CEILING                                               17
Broken Curb                                           17
Failed Street Repair                                  16
MOLD                                                  16
Leak (Use Comments) (WA2)                             15
Street Flooding (SJ)                                  15
WALL                                                  15
ENTIRE BUILDING                                       15
No Certificate Of Occupancy/Illegal/Contrary To CO    15
Pothole                                               14
Branch or Limb Has Fallen Down                        14
DAMP SPOT                                             14
Derelict Vehicles                                     14
HEAVY FLOW                                            13
Catch Basin Clogged/Flooding (Use Comments) (SC)      13
SLOW LEAK                                             13
Structure - Outdoors                                  13
Work Without A Permit - Occupied Multiple Dwelling    13
Illegal Hotel Rooms In Residential Building           12
Bodega, Deli, or Convenience Store                    12
APARTMENT ONLY                                        12
Defective Hardware                                    12
Dog                                                   12
With License Plate                                    12
Name: resolution_description, dtype: int64

In [101]:
combo_resolution = (
    df_core[df_core['resolution_description'].notna()]
    .groupby(['complaint_type', 'descriptor'])['resolution_description']
    .nunique()
    .sort_values(ascending=False)
)

print("Total complaint + descriptor combinations:", len(combo_resolution))

print("\nTop 30 combinations by resolution diversity:")
print(combo_resolution.head(30))

Total complaint + descriptor combinations: 748

Top 30 combinations by resolution diversity:
complaint_type                           descriptor
Sidewalk Condition                       Broken Sidewalk                                          26
Street Condition                         Cave-in                                                  22
Building/Use                             Illegal Conversion Of Residential Building/Space         18
Street Condition                         Rough, Pitted or Cracked Roads                           18
PAINT/PLASTER                            CEILING                                                  17
Curb Condition                           Broken Curb                                              17
Street Condition                         Failed Street Repair                                     16
UNSANITARY CONDITION                     MOLD                                                     16
PAINT/PLASTER                            WALL                                                     15
Sewer                                    Street Flooding (SJ)                                     15
HEAT/HOT WATER                           ENTIRE BUILDING                                          15
Water System                             Leak (Use Comments) (WA2)                                15
Building/Use                             No Certificate Of Occupancy/Illegal/Contrary To CO       15
Dirty Condition                          Trash                                                    14
WATER LEAK                               DAMP SPOT                                                14
Derelict Vehicles                        Derelict Vehicles                                        14
Damaged Tree                             Branch or Limb Has Fallen Down                           14
Sewer                                    Catch Basin Clogged/Flooding (Use Comments) (SC)         13
Real Time Enforcement                    Work Without A Permit - Occupied Multiple Dwelling       13
WATER LEAK                               HEAVY FLOW                                               13
                                         SLOW LEAK                                                13
Maintenance or Facility                  Structure - Outdoors                                     13
Special Projects Inspection Team (SPIT)  Illegal Hotel Rooms In Residential Building              12
PLUMBING                                 WATER SUPPLY                                             12
Plumbing                                 Failure To Retain Water/Improper Drainage- (LL103/89)    12
Abandoned Vehicle                        With License Plate                                       12
Consumer Complaint                       Bodega, Deli, or Convenience Store                       12
General Construction/Plumbing            Cons - Contrary/Beyond Approved Plans/Permits            12
                                         Building Shaking/Vibrating/Structural Stability          12
HEAT/HOT WATER                           APARTMENT ONLY                                           12
Name: resolution_description, dtype: int64

In [102]:
combo_stats = (
    df_core[df_core['resolution_description'].notna()]
    .groupby(['complaint_type', 'descriptor'])
    .agg(
        total_cases=('unique_key', 'count'),
        unique_resolutions=('resolution_description', 'nunique')
    )
    .sort_values(
        ['unique_resolutions', 'total_cases'],
        ascending=[False, False]
    )
)

print("Total combinations:", len(combo_stats))

print("\nTop 30 combinations:")
print(combo_stats.head(30))

Total combinations: 748

Top 30 combinations:
                                                                                            total_cases  \
complaint_type                          descriptor
Sidewalk Condition                      Broken Sidewalk                                             312
Street Condition                        Cave-in                                                     716
Building/Use                            Illegal Conversion Of Residential Building/Space            296
Street Condition                        Rough, Pitted or Cracked Roads                              162
PAINT/PLASTER                           CEILING                                                     845
Curb Condition                          Broken Curb                                                 128
UNSANITARY CONDITION                    MOLD                                                        941
Street Condition                        Failed Street Repair                                        195
HEAT/HOT WATER                          ENTIRE BUILDING                                            6457
PAINT/PLASTER                           WALL                                                        793
Water System                            Leak (Use Comments) (WA2)                                   300
Sewer                                   Street Flooding (SJ)                                        172
Building/Use                            No Certificate Of Occupancy/Illegal/Contrary To CO           87
Dirty Condition                         Trash                                                      2266
Derelict Vehicles                       Derelict Vehicles                                          1114
Damaged Tree                            Branch or Limb Has Fallen Down                              411
WATER LEAK                              DAMP SPOT                                                   200
                                        HEAVY FLOW                                                  614
                                        SLOW LEAK                                                   523
Sewer                                   Catch Basin Clogged/Flooding (Use Comments) (SC)            276
Real Time Enforcement                   Work Without A Permit - Occupied Multiple Dwelling          158
Maintenance or Facility                 Structure - Outdoors                                         75
HEAT/HOT WATER                          APARTMENT ONLY                                             3337
Abandoned Vehicle                       With License Plate                                         2099
PLUMBING                                WATER SUPPLY                                                631
General Construction/Plumbing           Building Shaking/Vibrating/Structural Stability             118
Special Projects Inspection Team (SPIT) Illegal Hotel Rooms In Residential Building                  48
General Construction/Plumbing           Cons - Contrary/Beyond Approved Plans/Permits                43
Consumer Complaint                      Bodega, Deli, or Convenience Store                           35
Plumbing                                Failure To Retain Water/Improper Drainage- (LL1...           33

                                                                                            unique_resolutions
complaint_type                          descriptor
Sidewalk Condition                      Broken Sidewalk                                                     26
Street Condition                        Cave-in                                                             22
Building/Use                            Illegal Conversion Of Residential Building/Space                    18
Street Condition                        Rough, Pitted or Cracked Roads                                      18
PAINT/PLASTER                           CEILING                                                             17
Curb Condition                          Broken Curb                                                         17
UNSANITARY CONDITION                    MOLD                                                                16
Street Condition                        Failed Street Repair                                                16
HEAT/HOT WATER                          ENTIRE BUILDING                                                     15
PAINT/PLASTER                           WALL                                                                15
Water System                            Leak (Use Comments) (WA2)                                           15
Sewer                                   Street Flooding (SJ)                                                15
Building/Use                            No Certificate Of Occupancy/Illegal/Contrary To CO                  15
Dirty Condition                         Trash                                                               14
Derelict Vehicles                       Derelict Vehicles                                                   14
Damaged Tree                            Branch or Limb Has Fallen Down                                      14
WATER LEAK                              DAMP SPOT                                                           14
                                        HEAVY FLOW                                                          13
                                        SLOW LEAK                                                           13
Sewer                                   Catch Basin Clogged/Flooding (Use Comments) (SC)                    13
Real Time Enforcement                   Work Without A Permit - Occupied Multiple Dwelling                  13
Maintenance or Facility                 Structure - Outdoors                                                13
HEAT/HOT WATER                          APARTMENT ONLY                                                      12
Abandoned Vehicle                       With License Plate                                                  12
PLUMBING                                WATER SUPPLY                                                        12
General Construction/Plumbing           Building Shaking/Vibrating/Structural Stability                     12
Special Projects Inspection Team (SPIT) Illegal Hotel Rooms In Residential Building                         12
General Construction/Plumbing           Cons - Contrary/Beyond Approved Plans/Permits                       12
Consumer Complaint                      Bodega, Deli, or Convenience Store                                  12
Plumbing                                Failure To Retain Water/Improper Drainage- (LL1...                  12

In [103]:
resolution_distribution = pd.cut(
    combo_stats['unique_resolutions'],
    bins=[0, 1, 3, 5, 10, float('inf')],
    labels=[
        '1 resolution',
        '2-3 resolutions',
        '4-5 resolutions',
        '6-10 resolutions',
        '11+ resolutions'
    ]
)

distribution_counts = resolution_distribution.value_counts().sort_index()

distribution_percent = (
    distribution_counts / len(combo_stats) * 100
).round(2)

resolution_summary = pd.DataFrame({
    'combinations': distribution_counts,
    'percentage': distribution_percent
})

resolution_summary

                    combinations  percentage
unique_resolutions
1 resolution                 241       32.22
2-3 resolutions              175       23.40
4-5 resolutions              117       15.64
6-10 resolutions             172       22.99
11+ resolutions               43        5.75

In [104]:
# For each complaint + descriptor combination,
# calculate how many cases belong to each resolution.
combo_resolution_counts = (
    df_core[df_core['resolution_description'].notna()]
    .groupby(
        ['complaint_type', 'descriptor', 'resolution_description']
    )
    .size()
    .reset_index(name='resolution_cases')
)

print("Total complaint-descriptor-resolution combinations:",
      len(combo_resolution_counts))

print("\nTop 30 most frequent resolution outcomes:")
print(
    combo_resolution_counts
    .sort_values('resolution_cases', ascending=False)
    .head(30)
)

Total complaint-descriptor-resolution combinations: 3088

Top 30 most frequent resolution outcomes:
                complaint_type                     descriptor  \
2506          Street Condition                        Pothole
1685       Noise - Residential               Loud Music/Party
1164            HEAT/HOT WATER                ENTIRE BUILDING
2730  Traffic Signal Condition                     Controller
2500          Street Condition                        Pothole
1271           Illegal Parking                Blocked Hydrant
1683       Noise - Residential               Loud Music/Party
1675       Noise - Residential               Banging/Pounding
1270           Illegal Parking                Blocked Hydrant
151           Blocked Driveway                      No Access
1154            HEAT/HOT WATER                ENTIRE BUILDING
150           Blocked Driveway                      No Access
1712   Noise - Street/Sidewalk               Loud Music/Party
1684       Noise - Residential               Loud Music/Party
1353           Illegal Parking  Posted Parking Sign Violation
1673       Noise - Residential               Banging/Pounding
1163            HEAT/HOT WATER                ENTIRE BUILDING
1710   Noise - Street/Sidewalk               Loud Music/Party
1355           Illegal Parking  Posted Parking Sign Violation
1146            HEAT/HOT WATER                 APARTMENT ONLY
1149            HEAT/HOT WATER                 APARTMENT ONLY
1351           Illegal Parking  Posted Parking Sign Violation
1156            HEAT/HOT WATER                ENTIRE BUILDING
36           Abandoned Vehicle             With License Plate
1674       Noise - Residential               Banging/Pounding
1356           Illegal Parking  Posted Parking Sign Violation
725            Dirty Condition                          Trash
2568    Street Light Condition               Street Light Out
1195         Highway Condition              Pothole - Highway
1157            HEAT/HOT WATER                ENTIRE BUILDING

                                 resolution_description  resolution_cases
2506  The Department of Transportation inspected thi...              2780
1685  The New York City Police Department responded ...              2350
1164  This complaint is a duplicate of a building-wi...              2167
2730  Service Request status for this request is ava...              2158
2500  The Department of Transportation determined th...              1902
1271  The New York City Police Department responded ...              1518
1683  The New York City Police Department responded ...              1405
1675  The New York City Police Department responded ...              1318
1270  The New York City Police Department responded ...              1290
151   The New York City Police Department responded ...              1279
1154  HPD responded to a complaint of no heat or hot...              1219
150   The New York City Police Department responded ...              1162
1712  The New York City Police Department responded ...              1122
1684  The New York City Police Department responded ...              1094
1353  The New York City Police Department responded ...               989
1673  The New York City Police Department responded ...               962
1163  The following complaint conditions are still o...               802
1710  The New York City Police Department responded ...               799
1355  The New York City Police Department responded ...               794
1146  The Department of Housing Preservation and Dev...               775
1149  This complaint is a duplicate of a building-wi...               749
1351  The New York City Police Department responded ...               748
1156  The Department of Housing Preservation and Dev...               743
36    The New York City Police Department responded ...               729
1674  The New York City Police Department responded ...               724
1356  The New York City Police Department responded ...               687
725   The Department of Sanitation investigated this...               661
2568  Service Request status for this request is ava...               634
1195  The Department of Transportation has completed...               623
1157  The Department of Housing Preservation and Dev...               613

In [105]:
# Count cases for every complaint + descriptor + resolution
resolution_support = (
    df_core[df_core['resolution_description'].notna()]
    .groupby(
        ['complaint_type', 'descriptor', 'resolution_description']
    )
    .size()
    .reset_index(name='resolution_cases')
)

# Number of resolutions with at least 5 historical examples
supported_resolution_counts = (
    resolution_support
    .assign(supported=lambda x: x['resolution_cases'] >= 5)
    .groupby(['complaint_type', 'descriptor'])
    .agg(
        total_resolutions=('resolution_description', 'nunique'),
        resolutions_with_5plus_cases=('supported', 'sum')
    )
)

supported_resolution_counts['support_ratio'] = (
    supported_resolution_counts['resolutions_with_5plus_cases']
    / supported_resolution_counts['total_resolutions']
)

print("Top 30 complaint-descriptor combinations by supported resolution diversity:")
print(
    supported_resolution_counts
    .sort_values(
        ['resolutions_with_5plus_cases', 'total_resolutions'],
        ascending=False
    )
    .head(30)
)

Top 30 complaint-descriptor combinations by supported resolution diversity:
                                                                                total_resolutions  \
complaint_type                descriptor
HEAT/HOT WATER                ENTIRE BUILDING                                                  15
Street Condition              Cave-in                                                          22
Dirty Condition               Trash                                                            14
Street Condition              Rough, Pitted or Cracked Roads                                   18
PAINT/PLASTER                 WALL                                                             15
Derelict Vehicles             Derelict Vehicles                                                14
HEAT/HOT WATER                APARTMENT ONLY                                                   12
Street Condition              Failed Street Repair                                             16
UNSANITARY CONDITION          MOLD                                                             16
Sidewalk Condition            Broken Sidewalk                                                  26
PAINT/PLASTER                 CEILING                                                          17
WATER LEAK                    HEAVY FLOW                                                       13
                              SLOW LEAK                                                        13
Abandoned Vehicle             With License Plate                                               12
DOOR/WINDOW                   WINDOW FRAME                                                     11
General Construction/Plumbing Building Permit - None                                           11
Illegal Dumping               Removal Request                                                  11
Street Condition              Pothole                                                          11
Noise - Residential           Banging/Pounding                                                 10
                              Loud Music/Party                                                 10
Building/Use                  Illegal Conversion Of Residential Building/Space                 18
Damaged Tree                  Branch or Limb Has Fallen Down                                   14
WATER LEAK                    DAMP SPOT                                                        14
PLUMBING                      WATER SUPPLY                                                     12
ELECTRIC                      POWER OUTAGE                                                     11
Illegal Parking               Posted Parking Sign Violation                                    11
Blocked Driveway              No Access                                                        10
Noise - Commercial            Loud Music/Party                                                 10
Street Sweeping Complaint     Inadequate Sweeping                                              10
APPLIANCE                     ELECTRIC/GAS RANGE                                                9

                                                                                resolutions_with_5plus_cases  \
complaint_type                descriptor
HEAT/HOT WATER                ENTIRE BUILDING                                                             14
Street Condition              Cave-in                                                                     13
Dirty Condition               Trash                                                                       12
Street Condition              Rough, Pitted or Cracked Roads                                              11
PAINT/PLASTER                 WALL                                                                        11
Derelict Vehicles             Derelict Vehicles                                                           11
HEAT/HOT WATER                APARTMENT ONLY                                                              11
Street Condition              Failed Street Repair                                                        10
UNSANITARY CONDITION          MOLD                                                                        10
Sidewalk Condition            Broken Sidewalk                                                              9
PAINT/PLASTER                 CEILING                                                                      9
WATER LEAK                    HEAVY FLOW                                                                   9
                              SLOW LEAK                                                                    9
Abandoned Vehicle             With License Plate                                                           9
DOOR/WINDOW                   WINDOW FRAME                                                                 9
General Construction/Plumbing Building Permit - None                                                       9
Illegal Dumping               Removal Request                                                              9
Street Condition              Pothole                                                                      9
Noise - Residential           Banging/Pounding                                                             9
                              Loud Music/Party                                                             9
Building/Use                  Illegal Conversion Of Residential Building/Space                             8
Damaged Tree                  Branch or Limb Has Fallen Down                                               8
WATER LEAK                    DAMP SPOT                                                                    8
PLUMBING                      WATER SUPPLY                                                                 8
ELECTRIC                      POWER OUTAGE                                                                 8
Illegal Parking               Posted Parking Sign Violation                                                8
Blocked Driveway              No Access                                                                    8
Noise - Commercial            Loud Music/Party                                                             8
Street Sweeping Complaint     Inadequate Sweeping                                                          8
APPLIANCE                     ELECTRIC/GAS RANGE                                                           8

                                                                                support_ratio
complaint_type                descriptor
HEAT/HOT WATER                ENTIRE BUILDING                                        0.933333
Street Condition              Cave-in                                                0.590909
Dirty Condition               Trash                                                  0.857143
Street Condition              Rough, Pitted or Cracked Roads                         0.611111
PAINT/PLASTER                 WALL                                                   0.733333
Derelict Vehicles             Derelict Vehicles                                      0.785714
HEAT/HOT WATER                APARTMENT ONLY                                         0.916667
Street Condition              Failed Street Repair                                   0.625000
UNSANITARY CONDITION          MOLD                                                   0.625000
Sidewalk Condition            Broken Sidewalk                                        0.346154
PAINT/PLASTER                 CEILING                                                0.529412
WATER LEAK                    HEAVY FLOW                                             0.692308
                              SLOW LEAK                                              0.692308
Abandoned Vehicle             With License Plate                                     0.750000
DOOR/WINDOW                   WINDOW FRAME                                           0.818182
General Construction/Plumbing Building Permit - None                                 0.818182
Illegal Dumping               Removal Request                                        0.818182
Street Condition              Pothole                                                0.818182
Noise - Residential           Banging/Pounding                                       0.900000
                              Loud Music/Party                                       0.900000
Building/Use                  Illegal Conversion Of Residential Building/Space       0.444444
Damaged Tree                  Branch or Limb Has Fallen Down                         0.571429
WATER LEAK                    DAMP SPOT                                              0.571429
PLUMBING                      WATER SUPPLY                                           0.666667
ELECTRIC                      POWER OUTAGE                                           0.727273
Illegal Parking               Posted Parking Sign Violation                          0.727273
Blocked Driveway              No Access                                              0.800000
Noise - Commercial            Loud Music/Party                                       0.800000
Street Sweeping Complaint     Inadequate Sweeping                                    0.800000
APPLIANCE                     ELECTRIC/GAS RANGE                                     0.888889

In [106]:
usable_cases = df_core[
    (df_core['status'] == 'Closed') &
    (df_core['resolution_description'].notna()) &
    (df_core['resolution_description'].str.strip().str.upper() != 'N/A')
].copy()

print("Total records:", len(df_core))
print("Usable historical cases:", len(usable_cases))
print("Percentage usable:", round(len(usable_cases) / len(df_core) * 100, 2), "%")

Total records: 100000
Usable historical cases: 95987
Percentage usable: 95.99 %

In [107]:
rag_columns = [
    'complaint_type',
    'descriptor',
    'borough',
    'resolution_description'
]

rag_cases = usable_cases[rag_columns].copy()

print("RAG cases:", len(rag_cases))

print("\nExact duplicate rows:")
print(rag_cases.duplicated().sum())

print("\nUnique case representations:")
print(rag_cases.drop_duplicates().shape[0])

RAG cases: 95987

Exact duplicate rows:
88749

Unique case representations:
7238

In [108]:
pattern_stats = {
    "Unique complaint + descriptor + resolution": (
        usable_cases[
            ['complaint_type', 'descriptor', 'resolution_description']
        ].drop_duplicates().shape[0]
    ),

    "Unique complaint + descriptor + borough + resolution": (
        usable_cases[
            ['complaint_type', 'descriptor', 'borough', 'resolution_description']
        ].drop_duplicates().shape[0]
    )
}

for key, value in pattern_stats.items():
    print(f"{key}: {value}")

Unique complaint + descriptor + resolution: 2929
Unique complaint + descriptor + borough + resolution: 7238

In [109]:
resolution_stats = (
    usable_cases['resolution_description']
    .value_counts()
    .reset_index()
)

resolution_stats.columns = ['resolution_description', 'case_count']

print("Unique resolution descriptions:", len(resolution_stats))

print("\nResolution frequency distribution:")
print(resolution_stats.head(50).to_string(index=False))

Unique resolution descriptions: 439

Resolution frequency distribution:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resolution_description  case_count
                                                                                                           The New York City Police Department responded to the complaint and with the information available observed no evidence of a criminal violation at that time. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. If necessary, your complaint may be referred to your local precinct's special operations units (Quality of Life, etc.). We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.       10723
The New York City Police Department responded to the complaint and their investigation determined that no criminal violation existed. The condition was corrected without the need to issue a summons or effect an arrest. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. If necessary, your complaint may be referred to your local precinct's special operations units (Quality of Life, etc.). Thank you for your attention to this matter. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.        9040
                                                                                                                                                                                                                                                        The New York City Police Department responded to the complaint and their investigation determined that police action was not necessary. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.        6347
                                                                                                                                                                                                                                                                          The New York City Police Department responded to the complaint and observed no criminal violation upon their arrival. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.        6071
                                                                                                                                                                                                                                                                                                                                              The New York City Police Department responded to the complaint and their investigation determined that a violation of law occurred. Police issued a summons in response to the complaint. Thank you for attention to this matter. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.        5878
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    HPD conducted an inspection of this complaint. The conditions observed by the inspector did not violate the housing laws enforced by HPD. The complaint has been closed.        3904
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Service Request status for this request is available on the Department of Transportationâs website. Please click the âLearn Moreâ link below.        3694
                                                                                                                                                                                                         This complaint is a duplicate of a building-wide condition already reported by another tenant.  The original complaint is still open, and HPD may only need to confirm that the condition exists by inspecting one apartment.  If we cannot contact the tenant from the original complaint or get access to that apartment, HPD may attempt to contact the person who filed this complaint to verify the correction of the condition or may conduct an inspection of your unit. You can check HPDONLINE to see if a        3077
                                                                                                                                                                                                        HPD inspected this condition so the complaint has been closed. Violations were issued. The law provides the property owner time to correct the condition(s).  Violation descriptions and the dates for the property owner to correct any violations are available at HPDONLINE.  If the owner has not corrected the condition by the date provided, you may wish to bring a case in housing court seeking the correction of these conditions.To find out more about how to start a housing court case, visit HPD's w        2864
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         The Department of Transportation inspected this complaint and repaired the problem.        2780
                                                                                                                                                                                                                                                                                                                                                                                     HPD attempted to conduct an inspection in response to this complaint, but was unable to complete the inspection. Please submit a new service request with 311 if the condition still exists. For more information on the reason why HPD was unable to inspect, contact HPD at the Tenant Information Messaging Service at 212-863-4951.        2745
                                                                                                                                                                                                                                                                                                               An HPD Inspector was not able to gain access to inspect this complaint. The Inspector left a card at the time of the inspection and a letter was sent from HPD after the inspection attempt to encourage you to call to schedule an inspection. HPD did not receive a timely response from you and the complaint has been closed. Please submit a new service request with 311 if the condition still exists.        2066
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  The Department of Transportation determined that this complaint is a duplicate of a previously filed complaint. The original complaint is being addressed.        1901
                                                                                                                                                                                                                                                                                                                                      HPD responded to a complaint of no heat or hot water in the building. An occupant of the building confirmed heat and hot water had been restored when the Inspector attempted to conduct the inspection or contacted you at the phone number associated with the complaint. The complaint has been closed. Please submit a new service request with 311 if the condition still exists.        1547
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            The Department of Sanitation investigated this complaint and found no condition at the location.        1489
                                                                                                                                                                                         The New York City Police Department responded to the complaint but officers were unable to gain entry into the premises. If the problem persists, please contact 311 to create another complaint and ensure that contact information (e.g., buzzer number, phone number, etc.) is available to assist the responding officers in gaining entry to properly investigate the complaint.  We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.        1356
                                                                                                                                                                                                                                                                                                                                                                                                                                                       The Department of Housing Preservation and Development was not able to gain access to your apartment or others in the building to inspect for a lack of heat or hot water. The complaint has been closed. If the condition still exists, please file a new complaint.        1128
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  HPD called the telephone number on file for this complaint.  Someone at that number indicated that the condition was corrected. The complaint has been closed. Please submit a new service request with 311 if the condition still exists.        1111
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      The Department of Transportation has completed the request or corrected the condition.        1092
                                                                                                                                                                                                                                                                                                                                                                                            The Department of Housing Preservation and Development conducted or attempted to conduct an inspection.  More information about inspection results can be found through HPD's website at www.nyc.gov/hpd by using HPDONLINE (enter your address on the home page) and entering your SR number under the complaint status option.        1001
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          The Department of Sanitation cleaned the location.         967
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            The Department of Sanitation investigated this complaint and found no violation at the location.         944
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                The Department of Buildings investigated this complaint and determined that no further action was necessary.         933
                                                                                                                                                                                                                                                                                                                                                                           The Department of Environmental Protection (DEP) didn't observe a violation of the NYC Air or Noise Code at the time of inspection and couldn't issue a summons.  If the problem still exists, please go to nyc.gov/311 or call 311 to file a new Service Request. If you're outside of New York City, please call (212) NEW-YORK (212-639-9675).         929
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        The Department of Environmental Protection determined that this complaint is a duplicate of a previously filed complaint. The original complaint is being addressed.         834
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        The Department of Housing Preservation and Development inspected the following conditions. No violations were issued. The complaint has been closed.         801

In [110]:
resolution_counts = (
    usable_cases['resolution_description']
    .value_counts()
)

for n in [5, 10, 20, 50, 100]:
    covered = resolution_counts.head(n).sum()
    percentage = covered / len(usable_cases) * 100

    print(
        f"Top {n:3} resolutions: "
        f"{covered:5} cases "
        f"({percentage:.2f}%)"
    )

Top   5 resolutions: 38059 cases (39.65%)
Top  10 resolutions: 54378 cases (56.65%)
Top  20 resolutions: 69814 cases (72.73%)
Top  50 resolutions: 84722 cases (88.26%)
Top 100 resolutions: 91565 cases (95.39%)

In [111]:
df_core['created_date'] = pd.to_datetime(df_core['created_date'])

monthly_counts = (
    df_core
    .groupby(df_core['created_date'].dt.to_period('M'))
    .size()
)

print("Monthly ticket counts:")
print(monthly_counts)

print("\nNumber of months:", len(monthly_counts))

Monthly ticket counts:
created_date
2026-03    100000
Freq: M, dtype: int64

Number of months: 1

In [112]:
#new findings

In [113]:
# Measure the variation added by descriptor_2

usable = df.dropna(subset=['resolution_description']).copy()

# Without descriptor_2
base_cols = [
    'complaint_type',
    'descriptor',
    'resolution_description'
]

# With descriptor_2
d2_cols = [
    'complaint_type',
    'descriptor',
    'descriptor_2',
    'resolution_description'
]

base_unique = usable.drop_duplicates(subset=base_cols).shape[0]
d2_unique = usable.drop_duplicates(subset=d2_cols).shape[0]

print("Total usable records:", len(usable))
print()

print("WITHOUT descriptor_2:")
print("Unique representations:", base_unique)
print("Duplicate records:", len(usable) - base_unique)

print()

print("WITH descriptor_2:")
print("Unique representations:", d2_unique)
print("Duplicate records:", len(usable) - d2_unique)

print()

print("Additional unique representations from descriptor_2:",
      d2_unique - base_unique)

print("Percentage increase:",
      round((d2_unique - base_unique) / base_unique * 100, 2), "%")

Total usable records: 99130

WITHOUT descriptor_2:
Unique representations: 3088
Duplicate records: 96042

WITH descriptor_2:
Unique representations: 4330
Duplicate records: 94800

Additional unique representations from descriptor_2: 1242
Percentage increase: 40.22 %

In [114]:
# How much does descriptor_2 differentiate the same complaint + descriptor?

d2_variation = (
    usable.groupby(['complaint_type', 'descriptor'])['descriptor_2']
    .nunique(dropna=True)
    .reset_index(name='unique_descriptor_2')
)

print("Complaint + descriptor combinations:", len(d2_variation))

print("\nDistribution of descriptor_2 variation:")
print(d2_variation['unique_descriptor_2'].value_counts().sort_index())

print("\nCombinations with multiple descriptor_2 values:")
print(
    d2_variation[d2_variation['unique_descriptor_2'] > 1]
    .sort_values('unique_descriptor_2', ascending=False)
    .head(20)
)

Complaint + descriptor combinations: 748

Distribution of descriptor_2 variation:
unique_descriptor_2
0     149
1     402
2      91
3      33
4      26
5      12
6       8
7       7
8       4
9       6
10      6
11      1
13      2
16      1
Name: count, dtype: int64

Combinations with multiple descriptor_2 values:
                 complaint_type                          descriptor  \
370     Maintenance or Facility                Structure - Outdoors
113          Consumer Complaint              Other Store (Non-Food)
77           Consumer Complaint  Bodega, Deli, or Convenience Store
103          Consumer Complaint                      Hotel or Motel
146                Damaged Tree      Branch or Limb Has Fallen Down
316             Illegal Parking         Parking Permit Improper Use
363     Maintenance or Facility               Graffiti or Vandalism
633              Taxi Complaint        Driver Complaint - Passenger
663    Traffic Signal Condition                   Pedestrian Signal
229  For Hire Vehicle Complaint        Driver Complaint - Passenger
454                    PLUMBING                              TOILET
124          Consumer Complaint        Supermarket or Grocery Store
678    Traffic Signal Condition                      Vehicle Signal
352               Lost Property                          Bag/Wallet
95           Consumer Complaint               Garage or Parking Lot
648    Traffic Signal Condition                          Controller
132          Consumer Complaint                     Used Car Dealer
700     Violation of Park Rules              Obstructing Public Use
448                    PLUMBING                          BASIN/SINK
147                Damaged Tree         Entire Tree Has Fallen Down

     unique_descriptor_2
370                   16
113                   13
77                    13
103                   11
146                   10
316                   10
363                   10
633                   10
663                   10
229                   10
454                    9
124                    9
678                    9
352                    9
95                     9
648                    9
132                    8
700                    8
448                    8
147                    8

In [115]:
# Does descriptor_2 create different resolution outcomes?

resolution_variation = (
    usable.groupby(
        ['complaint_type', 'descriptor', 'descriptor_2']
    )['resolution_description']
    .nunique()
    .reset_index(name='unique_resolutions')
)

print("Total complaint + descriptor + descriptor_2 groups:",
      len(resolution_variation))

print("\nDistribution of number of resolutions:")
print(
    resolution_variation['unique_resolutions']
    .value_counts()
    .sort_index()
)

print("\nGroups with multiple resolutions:")
print(
    resolution_variation[
        resolution_variation['unique_resolutions'] > 1
    ]
    .sort_values('unique_resolutions', ascending=False)
    .head(20)
)

Total complaint + descriptor + descriptor_2 groups: 1143

Distribution of number of resolutions:
unique_resolutions
1     536
2     173
3      99
4      88
5      53
6      38
7      35
8      50
9      20
10     18
11      8
12      5
13      5
14      6
15      3
16      4
18      1
22      1
Name: count, dtype: int64

Groups with multiple resolutions:
            complaint_type                                        descriptor  \
829       Street Condition                                           Cave-in
841       Street Condition                    Rough, Pitted or Cracked Roads
800     Sidewalk Condition                                   Broken Sidewalk
801     Sidewalk Condition                                   Broken Sidewalk
1068  UNSANITARY CONDITION                                              MOLD
833       Street Condition                              Failed Street Repair
1136          Water System                         Leak (Use Comments) (WA2)
799     Sidewalk Condition                                   Broken Sidewalk
792                  Sewer                              Street Flooding (SJ)
459         HEAT/HOT WATER                                   ENTIRE BUILDING
688          PAINT/PLASTER                                              WALL
460         HEAT/HOT WATER                                   ENTIRE BUILDING
461         HEAT/HOT WATER                                   ENTIRE BUILDING
1100            WATER LEAK                                         DAMP SPOT
684          PAINT/PLASTER                                           CEILING
779                  Sewer  Catch Basin Clogged/Flooding (Use Comments) (SC)
346        Dirty Condition                                             Trash
687          PAINT/PLASTER                                              WALL
1101            WATER LEAK                                        HEAVY FLOW
1103            WATER LEAK                                         SLOW LEAK

                          descriptor_2  unique_resolutions
829                                N/A                  22
841                                N/A                  18
800   4 + Residential Units/Commercial                  16
801                         City-Owned                  16
1068                               N/A                  16
833                                N/A                  16
1136                               WA2                  15
799              1-3 Residential Units                  15
792                                 SJ                  15
459                            NO HEAT                  14
688            CHIPPED/PEELING/FLAKING                  14
460           NO HEAT AND NO HOT WATER                  14
461                       NO HOT WATER                  14
1100              FROM WALL OR CEILING                  14
684                    HOLE OR CRACKED                  14
779                                 SC                  13
346      Not Cleaned by Property Owner                  13
687               BULGING/HOLE/CRACKED                  13
1101                AT WALL OR CEILING                  13
1103                AT WALL OR CEILING                  13

In [116]:
# Compare resolution diversity before and after adding descriptor_2

# WITHOUT descriptor_2
without_d2 = (
    usable.groupby(['complaint_type', 'descriptor'])
    ['resolution_description']
    .nunique()
)

# WITH descriptor_2
with_d2 = (
    usable.groupby(['complaint_type', 'descriptor', 'descriptor_2'])
    ['resolution_description']
    .nunique()
)

print("WITHOUT descriptor_2")
print("Groups:", len(without_d2))
print("Groups with multiple resolutions:",
      (without_d2 > 1).sum())
print("Percentage with multiple resolutions:",
      round((without_d2 > 1).mean() * 100, 2), "%")

print("\nWITH descriptor_2")
print("Groups:", len(with_d2))
print("Groups with multiple resolutions:",
      (with_d2 > 1).sum())
print("Percentage with multiple resolutions:",
      round((with_d2 > 1).mean() * 100, 2), "%")

WITHOUT descriptor_2
Groups: 748
Groups with multiple resolutions: 507
Percentage with multiple resolutions: 67.78 %

WITH descriptor_2
Groups: 1143
Groups with multiple resolutions: 607
Percentage with multiple resolutions: 53.11 %

In [117]:
print("Total usable records:", len(usable))

print("Records with descriptor_2:",
      usable['descriptor_2'].notna().sum())

print("Records missing descriptor_2:",
      usable['descriptor_2'].isna().sum())

print("Coverage:",
      round(usable['descriptor_2'].notna().mean() * 100, 2), "%")

Total usable records: 99130
Records with descriptor_2: 47368
Records missing descriptor_2: 51762
Coverage: 47.78 %

In [118]:
# Descriptor_2 coverage by complaint type

d2_coverage = (
    usable.groupby('complaint_type')
    .agg(
        total_cases=('descriptor_2', 'size'),
        with_descriptor_2=('descriptor_2', 'count')
    )
)

d2_coverage['coverage_percent'] = (
    d2_coverage['with_descriptor_2']
    / d2_coverage['total_cases']
    * 100
)

# Add volume so we can see both coverage and importance
d2_coverage = d2_coverage.sort_values(
    'total_cases',
    ascending=False
)

print(d2_coverage.head(30))

                               total_cases  with_descriptor_2  \
complaint_type
Illegal Parking                      15332                616
Noise - Residential                  10236                  0
HEAT/HOT WATER                        9794               9794
Street Condition                      7296               1651
Blocked Driveway                      4938                  0
Traffic Signal Condition              3300               3300
Noise - Street/Sidewalk               3211                  0
UNSANITARY CONDITION                  3004               3004
Dirty Condition                       2605               2605
Abandoned Vehicle                     2099                  0
PLUMBING                              2039               2039
PAINT/PLASTER                         1743               1743
Noise                                 1582               1582
Noise - Commercial                    1482                  0
WATER LEAK                            1337               1337
Water System                          1329               1329
DOOR/WINDOW                           1320               1320
Noise - Vehicle                       1308                  0
Derelict Vehicles                     1114                  0
Street Light Condition                1022               1022
GENERAL                               1007               1007
Sewer                                 1001               1001
Encampment                             973                  0
Illegal Dumping                        933                933
ELECTRIC                               883                883
FLOORING/STAIRS                        821                821
General Construction/Plumbing          820                  0
Highway Condition                      815                815
Damaged Tree                           733                733
Homeless Person Assistance             667                434

                               coverage_percent
complaint_type
Illegal Parking                        4.017741
Noise - Residential                    0.000000
HEAT/HOT WATER                       100.000000
Street Condition                      22.628838
Blocked Driveway                       0.000000
Traffic Signal Condition             100.000000
Noise - Street/Sidewalk                0.000000
UNSANITARY CONDITION                 100.000000
Dirty Condition                      100.000000
Abandoned Vehicle                      0.000000
PLUMBING                             100.000000
PAINT/PLASTER                        100.000000
Noise                                100.000000
Noise - Commercial                     0.000000
WATER LEAK                           100.000000
Water System                         100.000000
DOOR/WINDOW                          100.000000
Noise - Vehicle                        0.000000
Derelict Vehicles                      0.000000
Street Light Condition               100.000000
GENERAL                              100.000000
Sewer                                100.000000
Encampment                             0.000000
Illegal Dumping                      100.000000
ELECTRIC                             100.000000
FLOORING/STAIRS                      100.000000
General Construction/Plumbing          0.000000
Highway Condition                    100.000000
Damaged Tree                         100.000000
Homeless Person Assistance            65.067466

In [119]:
# How many actual records remain duplicated after using descriptor_2?

group_cols = [
    'complaint_type',
    'descriptor',
    'descriptor_2',
    'resolution_description'
]

group_sizes = (
    usable.groupby(group_cols, dropna=False)
    .size()
)

print("Total usable records:", len(usable))
print("Unique representations:", len(group_sizes))
print()

print("Representations occurring once:",
      (group_sizes == 1).sum())

print("Representations occurring more than once:",
      (group_sizes > 1).sum())

print()

print("Records belonging to duplicated representations:",
      group_sizes[group_sizes > 1].sum())

print("Percentage of records in duplicated representations:",
      round(
          group_sizes[group_sizes > 1].sum()
          / len(usable) * 100,
          2
      ), "%")

Total usable records: 99130
Unique representations: 4330

Representations occurring once: 1556
Representations occurring more than once: 2774

Records belonging to duplicated representations: 97574
Percentage of records in duplicated representations: 98.43 %

In [120]:
# Measure diversity of the actual input/query representation
# WITHOUT using the resolution as an input feature

input_cols = [
    'complaint_type',
    'descriptor',
    'descriptor_2'
]

input_groups = (
    usable.groupby(input_cols, dropna=False)
    .size()
    .sort_values(ascending=False)
)

print("Total usable records:", len(usable))
print("Unique input representations:", len(input_groups))
print()

print("Input representations occurring once:",
      (input_groups == 1).sum())

print("Input representations occurring more than once:",
      (input_groups > 1).sum())

print()

print("Top 20 most frequent input representations:")
print(input_groups.head(20))

Total usable records: 99130
Unique input representations: 1306

Input representations occurring once: 332
Input representations occurring more than once: 974

Top 20 most frequent input representations:
complaint_type            descriptor                     descriptor_2
Street Condition          Pothole                        NaN                         5633
Noise - Residential       Loud Music/Party               NaN                         5560
Illegal Parking           Blocked Hydrant                NaN                         4328
                          Posted Parking Sign Violation  NaN                         3918
Blocked Driveway          No Access                      NaN                         3754
Noise - Residential       Banging/Pounding               NaN                         3739
HEAT/HOT WATER            ENTIRE BUILDING                NO HEAT                     3140
Noise - Street/Sidewalk   Loud Music/Party               NaN                         2380
HEAT/HOT WATER            ENTIRE BUILDING                NO HEAT AND NO HOT WATER    2266
Abandoned Vehicle         With License Plate             NaN                         2099
Illegal Parking           Blocked Sidewalk               NaN                         1973
HEAT/HOT WATER            APARTMENT ONLY                 NO HEAT                     1884
Traffic Signal Condition  Controller                     Operating Improperly        1701
Dirty Condition           Trash                          Littering                   1404
Blocked Driveway          Partial Access                 NaN                         1184
Noise - Commercial        Loud Music/Party               NaN                         1114
Derelict Vehicles         Derelict Vehicles              NaN                         1114
HEAT/HOT WATER            ENTIRE BUILDING                NO HOT WATER                1051
Illegal Parking           Blocked Crosswalk              NaN                         1030
Encampment                N/A                            NaN                          973
dtype: int64

In [121]:
input_cols = ['complaint_type', 'descriptor', 'descriptor_2']
pattern_stats = (
    usable.groupby(input_cols)
    .agg(
        total_cases=('resolution_description', 'size'),
        unique_resolutions=('resolution_description', 'nunique'),
    )
)
# Also compute top-1 share
top1_share = (
    usable.groupby(input_cols)['resolution_description']
    .apply(lambda s: s.value_counts(normalize=True).iloc[0])
)
pattern_stats['top1_share'] = top1_share

In [122]:
pattern_stats.head(20)

                                                                                             total_cases  \
complaint_type   descriptor                                  descriptor_2
APPLIANCE        ELECTRIC/GAS RANGE                          CONTROL KNOB BROKEN OR MISSING           45
                                                             NO GAS                                    3
                                                             NO GAS OR ELECTRICITY                   196
                                                             NO STOVE KNOB COVERS                     10
                                                             OVEN DOOR MISSING OR BROKEN              59
                                                             PILOT LIGHT OUT                          54
                                                             RANGE/OVEN BROKEN OR MISSING              3
                 REFRIGERATOR                                BROKEN DOOR SEAL                        207
                                                             BROKEN OR MISSING                         3
Abandoned Bike   Chained to Public Property                  N/A                                      55
Air Quality      Air: Dust, Construction/Demolition (AE4)    AE4                                      19
                 Air: Dust, Other (Use Comments) (AE5)       AE5                                       2
                 Air: Odor, Nail Salon (AD8)                 AD8                                       2
                 Air: Odor, Sweet From Unknown Source (AZ1)  AZ1                                       1
                 Air: Odor/Fumes, Restaurant (AD2)           AD2                                      17
                 Air: Odor/Fumes, Vehicle Idling (AD3)       AD3                                     152
                 Air: Other Air Problem (Use Comments) (AZZ) AZZ                                       5
                 Air: Smoke, Chimney or vent (AS1)           AS1                                      14
                 Air: Smoke, Vehicular (AA4)                 AA4                                       2
Animal in a Park Animal Waste                                Dog                                      16

                                                                                             unique_resolutions  \
complaint_type   descriptor                                  descriptor_2
APPLIANCE        ELECTRIC/GAS RANGE                          CONTROL KNOB BROKEN OR MISSING                   5
                                                             NO GAS                                           3
                                                             NO GAS OR ELECTRICITY                            8
                                                             NO STOVE KNOB COVERS                             5
                                                             OVEN DOOR MISSING OR BROKEN                      6
                                                             PILOT LIGHT OUT                                  7
                                                             RANGE/OVEN BROKEN OR MISSING                     2
                 REFRIGERATOR                                BROKEN DOOR SEAL                                 9
                                                             BROKEN OR MISSING                                3
Abandoned Bike   Chained to Public Property                  N/A                                             11
Air Quality      Air: Dust, Construction/Demolition (AE4)    AE4                                              2
                 Air: Dust, Other (Use Comments) (AE5)       AE5                                              1
                 Air: Odor, Nail Salon (AD8)                 AD8                                              1
                 Air: Odor, Sweet From Unknown Source (AZ1)  AZ1                                              1
                 Air: Odor/Fumes, Restaurant (AD2)           AD2                                              3
                 Air: Odor/Fumes, Vehicle Idling (AD3)       AD3                                              2
                 Air: Other Air Problem (Use Comments) (AZZ) AZZ                                              2
                 Air: Smoke, Chimney or vent (AS1)           AS1                                              2
                 Air: Smoke, Vehicular (AA4)                 AA4                                              1
Animal in a Park Animal Waste                                Dog                                              2

                                                                                             top1_share
complaint_type   descriptor                                  descriptor_2
APPLIANCE        ELECTRIC/GAS RANGE                          CONTROL KNOB BROKEN OR MISSING    0.511111
                                                             NO GAS                            0.333333
                                                             NO GAS OR ELECTRICITY             0.260204
                                                             NO STOVE KNOB COVERS              0.300000
                                                             OVEN DOOR MISSING OR BROKEN       0.457627
                                                             PILOT LIGHT OUT                   0.370370
                                                             RANGE/OVEN BROKEN OR MISSING      0.666667
                 REFRIGERATOR                                BROKEN DOOR SEAL                  0.362319
                                                             BROKEN OR MISSING                 0.333333
Abandoned Bike   Chained to Public Property                  N/A                               0.400000
Air Quality      Air: Dust, Construction/Demolition (AE4)    AE4                               0.947368
                 Air: Dust, Other (Use Comments) (AE5)       AE5                               1.000000
                 Air: Odor, Nail Salon (AD8)                 AD8                               1.000000
                 Air: Odor, Sweet From Unknown Source (AZ1)  AZ1                               1.000000
                 Air: Odor/Fumes, Restaurant (AD2)           AD2                               0.882353
                 Air: Odor/Fumes, Vehicle Idling (AD3)       AD3                               0.552632
                 Air: Other Air Problem (Use Comments) (AZZ) AZZ                               0.800000
                 Air: Smoke, Chimney or vent (AS1)           AS1                               0.785714
                 Air: Smoke, Vehicular (AA4)                 AA4                               1.000000
Animal in a Park Animal Waste                                Dog                               0.937500

In [123]:
print("Total input patterns:", len(pattern_stats))

print("\nTop-1 share distribution:")
print(
    pd.cut(
        pattern_stats["top1_share"],
        bins=[0, 0.25, 0.50, 0.75, 0.90, 1.0],
        include_lowest=True
    ).value_counts().sort_index()
)

print("\nResolution diversity:")
print(
    pattern_stats["unique_resolutions"]
    .value_counts()
    .sort_index()
)

print("\nPatterns with multiple resolutions:",
      (pattern_stats["unique_resolutions"] > 1).sum())

print("Patterns with 3+ resolutions:",
      (pattern_stats["unique_resolutions"] >= 3).sum())

Total input patterns: 1143

Top-1 share distribution:
top1_share
(-0.001, 0.25]     31
(0.25, 0.5]       338
(0.5, 0.75]       152
(0.75, 0.9]        60
(0.9, 1.0]        562
Name: count, dtype: int64

Resolution diversity:
unique_resolutions
1     536
2     173
3      99
4      88
5      53
6      38
7      35
8      50
9      20
10     18
11      8
12      5
13      5
14      6
15      3
16      4
18      1
22      1
Name: count, dtype: int64

Patterns with multiple resolutions: 607
Patterns with 3+ resolutions: 434

In [124]:
pattern_stats['volume'] = pattern_stats['total_cases']
pattern_stats['bucket'] = pd.cut(
    pattern_stats['top1_share'],
    bins=[0, 0.25, 0.5, 0.75, 0.9, 1.0],
    labels=['very_diverse', 'diverse', 'moderate', 'near_det', 'deterministic']
)

# Volume-weighted distribution
volume_by_bucket = pattern_stats.groupby('bucket')['volume'].sum()
print(volume_by_bucket / volume_by_bucket.sum() * 100)

bucket
very_diverse     12.905337
diverse          56.998396
moderate         12.016551
near_det          5.060378
deterministic    13.019338
Name: volume, dtype: float64

/tmp/ipykernel_2114/3937412227.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  volume_by_bucket = pattern_stats.groupby('bucket')['volume'].sum()

In [125]:
pattern_stats.groupby('bucket')['total_cases'].describe()

/tmp/ipykernel_2114/771868197.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  pattern_stats.groupby('bucket')['total_cases'].describe()

               count        mean         std  min   25%   50%     75%     max
bucket
very_diverse    31.0  197.193548  359.253895  4.0  11.0  98.0  204.00  1884.0
diverse        338.0   79.878698  256.613173  2.0   4.0  15.0   53.75  3140.0
moderate       152.0   37.447368   76.176406  3.0   4.0  10.0   36.25   580.0
near_det        60.0   39.950000   96.080726  5.0   8.0  15.5   33.25   718.0
deterministic  562.0   10.973310   81.280468  1.0   1.0   1.0    3.00  1701.0

In [126]:
pattern_stats.nlargest(20, 'total_cases')[['complaint_type','descriptor','descriptor_2','total_cases','top1_share']]

KeyError: "['complaint_type', 'descriptor', 'descriptor_2'] not in index"

In [ ]:
closed_df = df[df["status"] == "Closed"].copy()

print("Closed tickets:", len(closed_df))
print("Shape:", closed_df.shape)

closed_df.to_csv("nyc_311_closed_tickets.csv", index=False)

print("Saved as: nyc_311_closed_tickets.csv")

In [130]:
columns = [
    "unique_key",
    "created_date",
    "closed_date",
    "complaint_type",
    "descriptor",
    "descriptor_2",
    "resolution_description"
]

closed_tickets = df[df["status"] == "Closed"][columns].copy()

closed_tickets.to_csv("closed_tickets_rag.csv", index=False)

print("Saved:", len(closed_tickets), "closed tickets")
print("Columns:", list(closed_tickets.columns))

Saved: 96628 closed tickets
Columns: ['unique_key', 'created_date', 'closed_date', 'complaint_type', 'descriptor', 'descriptor_2', 'resolution_description']